version: "3.8"

name: "sa-gpt"
services:
  privategpt:
    ports:
      - "8001:8001"
    image: boxedition/privategpt:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
